[extend]
useDefault = true

[allowlist]
paths = [
  '''vendor/''',
  '''node_modules/''',
  '''protected/config/''',
  '''protected/modules/rest/docs/''',
  '''protected/runtime/''',
  '''assets/''',
  '''.*/tests/.*''',
]
